# Apriori
Apriori is used to find frequent itemsets from data. It takes only two arguments: the data and the treshold about what is considered as frequent.

The algoritm first looks itemsets of size one. If the frequency in the records is higher than the treshold, the product will be involved in the next iteration.

Next, all itemsets of size two containing a product that exceeded the treshold in previous stage will be under investigation.

The process continues until no frequent itemsets are found or maximum combination length has been reached.

[Wikipedia has an example](https://en.wikipedia.org/wiki/Apriori_algorithm) that is easy to understand. The example for this code taken from `mlextend` tutorial [here](http://rasbt.github.io/mlxtend/user_guide/frequent_patterns/apriori/#api).

## Import

In [ ]:
from mlxtend.frequent_patterns import apriori
from mlxtend.preprocessing import TransactionEncoder
import pandas as pd

## Pre process data

In [19]:
data_values = [
    ['Milk', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
    ['Dill', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
    ['Milk', 'Apple', 'Kidney Beans', 'Eggs'],
    ['Milk', 'Unicorn', 'Corn', 'Kidney Beans', 'Yogurt'],
    ['Corn', 'Onion', 'Onion', 'Kidney Beans', 'Ice cream', 'Eggs']
]

#Turn the values to binaries
te = TransactionEncoder()
data_binary = te.fit(data_values).transform(data_values)
#Turn binary data to data frame
df = pd.DataFrame(data_binary, columns=te.columns_)
df.head(10)

,Apple,Corn,Dill,Eggs,Ice cream,Kidney Beans,Milk,Nutmeg,Onion,Unicorn,Yogurt
0,False,False,False,True,False,True,True,True,True,False,True
1,False,False,True,True,False,True,False,True,True,False,True
2,True,False,False,True,False,True,True,False,False,False,False
3,False,True,False,False,False,True,True,False,False,True,True
4,False,True,False,True,True,True,False,False,True,False,False

## Run apriori

In [17]:
#Get apriori results in data frame
df_apr = apriori(df, min_support=0.6, use_colnames=True)
df_apr

    support                     itemsets
0       0.8                       [Eggs]
1       1.0               [Kidney Beans]
2       0.6                       [Milk]
3       0.6                      [Onion]
4       0.6                     [Yogurt]
5       0.8         [Eggs, Kidney Beans]
6       0.6                [Eggs, Onion]
7       0.6         [Kidney Beans, Milk]
8       0.6        [Kidney Beans, Onion]
9       0.6       [Kidney Beans, Yogurt]
10      0.6  [Eggs, Kidney Beans, Onion]